### ISSUE TITLE
ONLINE REQUEST

### ISSUE THREAD

**Issue by xinlangzi** [xinlangzi/homey#12]
ONLINE REQUEST(用户输入后submit至企业Email，网站自行另加备份)
  * I’m expat
  * 业主委托
 

* I’m expat
     1. I want [下拉可选rent/buy/sell] a/an + [下拉可选上述PROPERTIES的七项+第八项Others]
     2. Bedrooms用户自行输入 [ ] ~[ ] ,不需要下拉选项；
     3. Bathrooms 用户自行输入 [ ] ~[ ] ,不需要下拉选项；
     4. Budget用户自行输入 [ ] ~[ ] ,不需要下拉选项；
     5. Term of Lease 用户自行输入 [date/month/year]  -- (光标点击输入时灰色小字消失)
     6. Name
     7. Email
     8. Mobile
     9. Any other additional requirements/comments? 用户自行输入, 预留长篇幅；
     ----1,2, 6,7,8标记为 * 且注明(Fields marked with star keys * are compulsory.)
     ----当用户选择1.为rent时,1~9全部列出；当用户选择1.为buy or sell时，5自行隐藏；

* 业主委托（中文显示）内含
     Name/姓名,
     Mobile/电话，
     Email电子邮件，三项均标记为 *
     意向：[请尽量将您有意出租或出售房源的小区名，门牌号，楼层，意向月租金/售价，屋内设施等信息描述详尽，我们会根据您的要求第一时间给您回复] (光标点击输入时灰色小字消失), 用户输入后submit至企业Email，网站自行另加备份；
     下方设FAQ(预留长篇幅给管理员自定义文字信息，内容不可复制粘贴)( faq-to-owner)

**Comment by haobole** [comment]
@xinlangzi ,

It looks like this is what I was working on when I became busy with other things. My work is not deployed, but if you check out iteration-2 branch and then go to http://localhost:3000/requests/new, you will see how far I got.
