### ISSUE TITLE
Add extra date field

### ISSUE THREAD

**Issue by xinlangzi** [xinlangzi/homey#13]
Add extra date field to property to indicate "being occupied until" for the property with Serviced Apartments type.

**Comment by haobole** [comment]
@xinlangzi , we already have "available date". What is the difference between "available date" and "being occupied until date"?

**Comment by xinlangzi** [comment]
@haobole 

I think "being occupied until date" mean

**Comment by xinlangzi** [comment]
available date= 更新至...日还没有租出，依然在招租；
being occupied until= 已经有人在租， 于...日后才重新出租

**Comment by xinlangzi** [comment]
@haobole 

We can still use available_date column with different label.

* For Serviced Apartment, we can use "Being Occupied Until" label. 
* For other type of properties, please use "Available Date". (For new property, default is current day)
