### ISSUE TITLE
News

### ISSUE THREAD

**Issue by xinlangzi** [xinlangzi/homey#14]
CRUD news on the backend. Think about to use rich text editor with photo support.

News新闻短讯；
--不可复制粘贴；
--短讯内容 图片+文字

**Comment by haobole** [comment]
@xinlangzi , this says CRUD news on the backend. Where should it be displayed on the frontend? Also, you say disallow copy and paste? You mean I need to block people from selecting the news text and then Ctrl-C or right-click copy?

**Comment by xinlangzi** [comment]
@haobole 

On the home page, there is a big gap on the right of latest properties. Please list last 10 news with a "more" link to a page with all news with pagination.

![image](https://cloud.githubusercontent.com/assets/1171370/7288923/8807be6e-e99b-11e4-8c43-3e62b93d3a3b.png)

For the block copy, you are right. Think about best way to block them. Remember the user are not technological IT guy. Assume they don't know how to use "inspect element". So just disallow ctrl-C and right click to copy.
