### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by xinlangzi** [xinlangzi/homey#21]
* [x] Slogan: normal style
* [x] Our Service into System Configuration(rich)
* [x] Contact Us into System* [x] Configuration(rich)
* [x] How to become VIP into System Configuration(rich)
* [x] 含免责条款 into System Configuration
* [x] FAQ to Owner into System Configuration(Disallow user to copy)
* [x] Make it more serious warning
* [x] Search Widget:
  * [x]   XIS Bus Stop
  * [x]   Move Property ID to new line with placeholder: (If you know the Property ID of the apartment you are looking for, type it in here and directly click ‘search')
* [x] Properties
  * [x]   Property ID(Auto generate: Letter and Digit)
  * [x]   Long Term Lease(default: checked)
  * [x]   Image Size Recommend
* [x] Online Request (Philip)
  * [x]   Budget: min max
  * [x]   Bedroom: min max
  * [x]   Bathroom: min max
* [x] Top Menu: add border radius to bottom
* [x] Property Info:
  * [x]   Keep slide right info when mouse is hover only for Serviced Department
  * [x]   Avoid the excerpt block the image
* [x] Display the weather on the Top left corner   (Philip)
* [x] Keywords for Google Search: (xiamen house, xiamen apartment, xiamen flat, xiamen condo) (Philip)
* [x] Water Marker with same font with Logo, Top font is Watford DB, the bottom font is USUZI. Make the letters more transparent.  (Philip)
* [x] Area:    (Philip)
  * [x]   Add description
  * [x]   Put behind the area on the home page
  * [x]   Put description on the search result page if area is filtered
* [x] Rename News to Resource (Philip)
* [x] Add Homeyagency Copyright Reserved at the end of each news  (Philip)
* [x] Dark the email font on the top navbar
* [x] reCAPTCHA from google is not accessible from China. Change to simple math questions.  (Philip)
* [x] Move the map out of the tab to the bottom
* [x] Order(Name, Property ID, Lease Start,Lease End, Landlord banking account info., amount of rent per period, period length, length of advance notice)
  * [x]   Add Fee (nested attributes form)[https://github.com/ncri/nested_form_fields]
         * Category (Rent, Internet, Elec, Water, Gas, Property Management Charge, Cable TV, Satellite TV)
         * Amount
         * Note
         * Paid
  * [x]   Auto Remind
* [x] 主页Logo下方的说明与LOGO帖得太近，请将说明下移或右移；
* [x] 网页标签的XiaMen .... 请改成Xiamen…
* [x] 由于字号太大略显得网页低端，请将图片网址水印再小一个字号；
* [x] 主页房源列表的房源标题字号设置成与[Area]字号大小相同，并设成小写；
* [x] 手机界面的主页上方的大菜单按钮栏排列混乱；
* [x] 目前管理员无法删除sublease和resoureces?

**Comment by xinlangzi** [comment]
@haobole 

I built the basic layout for Order and charge. You can continue on controller part if you work on it

**Comment by haobole** [comment]
@xinlangzi ,

I think I need to meet to go over the requirements for charges again. I cannot remember what you said. Also, I need to wait to do the google search stuff until after this is deployed to production. I do not want to have google indexing staging.homeyagency.com

**Comment by haobole** [comment]
@xinlangzi ,

I deployed my changes. Please review.

Are you planning to design the UI for when a VIP looks at an order?

**Comment by xinlangzi** [comment]
@haobole

Yes. I will design it. :) Thank you

**Comment by haobole** [comment]
@xinlangzi ,

I made the watermark only 25% opaque. Tell me if that is too light.

I also changed the captcha to math.

I deployed to staging.

I will do the Google optimization after we deploy to production.

Is there something else you wanted me to do?

**Comment by xinlangzi** [comment]
@haobole 

Can you help me to deploy to staging and production?

**Comment by haobole** [comment]
@xinlangzi ,

Bro, I think it would be better if you address this one " 手机界面的主页上方的大菜单按钮栏排列混乱；"

**Comment by xinlangzi** [comment]
@haobole

I solved this problem.

**Comment by xinlangzi** [comment]
* 主页area名称变成两行了，为保持整体美观，【区域名称+区域说明】仅限一行， 即使区域名称很长，留给说明部分的空间较短也无妨，我这里编辑时会尽可能用简洁的语言来表述区域说明;
* 当sign in/logout 时,主页最上方的绿色提示条将菜单遮挡了，请将绿提示条移至主页的最下方
* 请将主页房源展示图下方的 [surface area、total room]与[bedroom、bathroom]上下交换
* 编辑房源图片时，需要有设置封面图片的功能，当前无法在多张图片中挑选任一张做展示封面，
* 区域的小字说明部分，在与区域名称断开的情况下靠左排列（不放在居中）
* 现实情况中，有些房源照片是竖立着拍摄的，这类竖立照片上传后尺寸超出边框了， 
http://www.homeyagency.com/backend/properties/05769C 
例如链接的最后一张图，能否将竖立图片设置成和同行网站一样的排列方式（左右留空白，见图示）

**Comment by haobole** [comment]
@xinlangzi ,

I finished the two items you asked me to do and deployed to staging. Please review. You can also fix the two specs you maliciously broke :)
