### ISSUE TITLE
Property Search Widget

### ISSUE THREAD

**Issue by xinlangzi** [xinlangzi/homey#8]
* Bedrooms: Drop-down list (1 Br, 2 Brs, 3 Brs, 4 Brs, 5 Brs and 5 Brs+)
* Price Rang: Min to  Max(text field)
* District: Drop-down list
* Property Type: Drop-down list
* Feature: Only these fields( With Garden/Duplex/With Terrace/Unfurnished /Managed Compound/Short Term Lease)  Checkbox
* Property ID: Text field(Hint: If you know the Property ID of the apartment you are looking for, type it in here)

**Comment by haobole** [comment]
@xinlangzi ,

For the checkbox features, if the checkbox is UNCHECKED, which of these does the search mean?

1. Only return properties that do NOT have that feature OR
2. Return all properties regardless of the value of that feature.

**Comment by xinlangzi** [comment]
@haobole 

The answer is item 2.

**Comment by xinlangzi** [comment]
@haobole 

I found an issue on the search widget, if there are 7 bedrooms, the search is always nothing. There is problem about 5 Brs+. I think you need to use the ransack to extend scope for seach. 

For example:

```
  scope :outstanding, ->(t=true){
    joins(line_items: :customer_order).
    where("invoices.balance != 0").
    where("customer_orders.status != 4").
    where("customer_orders.order_type IN (?)", [0, 1, 6]).
    group("invoices.id") if t.to_boolean
  }
  def self.ransackable_scopes(auth=nil)
    [:outstanding]
  end
```

I will let you design.

**Comment by xinlangzi** [comment]
@haobole 

also I downgrade the ruby version, I don't know why my latest rvm does not have version 2.2.2.

**Comment by haobole** [comment]
@xinlangzi ,

I cannot duplicate this problem. At least on my machine and on the deployed version, my logic appears to be working: https://github.com/xinlangzi/homey/pull/16/files#diff-86181218e7fe54a052bb33ae00768943R24

Did you actually see incorrect SQL getting generated when you chose 5+?

**Comment by xinlangzi** [comment]
@haobole 

The SQL is right. But the select option is not kept after searching.

**Comment by haobole** [comment]
@xinlangzi ,

I understand now. Yes, I see that I need logic to INTERPRET the params as they are, not CHANGE the params. Thank you for bringing this to my attention.
